import React from 'react';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingBottom: 5,
  },
  header: {
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 2,
    paddingHorizontal: 4,
    fontWeight: 800,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#000000',
  },
  headerText: {
    fontSize: 20,
    color: '#000000',
    fontWeight: 'bold',
    paddingLeft: 20,
  },
  title: {
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 4,
    //backgroundColor: 'yellow',
  },
  titleText: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  input: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 45,
    marginTop: 10,
    //backgroundColor: 'orange',
  },
  inputText: {
    textAlign: 'center',
    textDecorationLine: 'none',
    justifyContent: 'center',
    width: '80%',
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 5,
    fontSize: 20,
    fontWeight: 'bold',
    backgroundColor: '#dddddd',
  },
  list: {
    width: '100%',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginTop: 5,
    paddingBottom: 20,
    zIndex: 5,
    //backgroundColor: 'pink',
  },
  item: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 300,
    height: 40,
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 5,
    paddingHorizontal: 5,
    marginBottom: 4,
    backgroundColor: '#cccccc',
  },
  itemText: {
    color: '#000000',
    fontSize: 15,
    fontWeight: 'bold',
  },
  summary: {
    flex: 1,
    width: '100%',
    backgroundColor: 'green',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
});
