export const testMeds = [
{
	id: "2MV2XRGwHIPQABgqheOy",
	name: "L-Dopa",
	description: "L-Dopa",
	form: "powder",
	measurement: "mg",
	schedule: "",
	occurance: 3,
	often: "hour",
	dosage: "200MG",
	sortOrder: 99,
},
{
	id: "8YDiybtkY1A8G41lKvRH",
	measurement: "ea",
	often: "daily",
	form: "capsule",
	occurance: 1,
	schedule: "",
	description: "Vitamin B Supplement",
	dosage: "1CAPSULE",
	name: "B-100",
	sortOrder: 99,
},
{
	id: "NzXSChCtVrDtmuPETxlB",
	form: "capsule",
	dosage: "1CAPSULE",
	schedule: "",
	description: "Vitamin C and Iron",
	measurement: "ea",
	name: "HemeVite Plus",
	often: "daily",
	occurance: 1,
	sortOrder: 99,
},
{
	id: "QfxfH6Hd6G3OsYageooB",
	description: "Carbidopa/Levodopa 25/100 mg",
	dosage: "1CAPSULE",
	name: "Carbidopa/Levodopa",
	measurement: "ea",
	often: "asneeded",
	schedule: "",
	form: "tablet",
	occurance: 1,
	sortOrder: 99,
},
{
	id: "Wjdmsajwd4w2CRkAmj4O",
	occurance: 4,
	name: "Alprazolam",
	schedule: "",
	description: "Xanax Generic 0.25 mg",
	often: "daily",
	dosage: "0.25MG",
	form: "tablet",
	measurement: "ea",
	sortOrder: 99,
},
{
	id: "bb51FRc0N2eYf3AznquT",
	form: "capsule",
	often: "daily",
	dosage: "1CAPSULE",
	schedule: "",
	occurance: 2,
	name: "FolACTIVE",
	measurement: "ea",
	description: "Methylated Folate",
	sortOrder: 99,
},
{
	id: "lUndouO1rxSDSApPw28r",
	name: "Amantadine",
	occurance: 3,
	dosage: "10ML",
	description: "Amantadine HCL",
	often: "daily",
	form: "liquid",
	schedule: "",
	measurement: "ml",
	sortOrder: 99,
},
{
	id: "mS773lbViziEhiAZJerX",
	often: "daily",
	name: "D3",
	form: "capsule",
	occurance: 1,
	schedule: "",
	measurement: "ea",
	description: "Vitamin D 125 mcg",
	dosage: "1CAPSULE",
	sortOrder: 99,
}
]