export const testUser = {
  awakeTime: '8:00AM',
  bedTime: '10:00PM',
  createdAt: 'Sat, 12 Feb 2022 01:18:54 GMT',
  description: 'some really handsome guy',
  displayName: 'newbie updated test',
  email: 'new@user.com',
  id: 'y3app4x43CVAGTBvUFHCJMiBIik2',
  providerId: 'password',
};

export const testMeds = [
  {
    description: 'Atenolol 100 mg',
    dosage: '100',
    form: 'tablet',
    isPaused: false,
    measurement: 'mg',
    name: 'Atenolol',
    brand: 'Atenolol',
    occurance: '1',
    often: 'daily',
    sortOrder: 1,
    times: '',
  },
  {
    description:    "Lisinopril 10 mg",
    dosage:    "10",
    form:    "tablet",
    id:    "l4sRXgQuQjd7DOLhqxUI",
    isPaused:    false,
    measurement:    "mg",
    name:    "Lisinopril",
    brand:    "Lisinopril",
    occurance:    "1",
    often:    "daily",
    sortOrder:    3,
    times:    "",
  },
  {
    brand:    "ALPRAZOLAM",
    description:    "",
    dosage:    "0.5MG",
    form:    "TABLET",
    isPaused:    false,
    name:    "ALPRAZOLAM",
    occurance:    4,
    often:    "daily",
    schedule: [
        "06:00 AM",
        "11:00 AM",
        "04:00 PM",
        "09:00 PM"
        ],
    sortOrder:    99,
    withMeals:    false,
  },
];
